#!/bin/zsh
#
# Based on:
# https://threkk.medium.com/how-to-use-bookmarks-in-bash-zsh-6b8074e40774
#
# This lets you quickly jump to bookmarked locations.
#
# Type:
#
#   bm <tab>
#
# ...to autocomplete on all of your bookmarks in the directory specified in
# `functions/_bm`. Typically I'm using it like:
#
#    bm dal<tab>
#
# ...to quickly jump into my dalmore bookmark.
#
# You can also pass to arguments to fuzzy find in the bookmarks directory.

if [ -z "$1" ]; then
    # Get the links in the bookmarks directory, strip the leading path,
    # pass to fzf and get the selected entry.
    selected=$(find "$HOME/.bookmarks" -type l \
               | sed "s|$HOME/.bookmarks/||" \
               | fzf)
else
    selected="$1"
fi

# Check that $selected is not empty, e.g. by Ctrl-C on while in fzf.
if [ -n "$selected" ]; then
    cd -P "$HOME/.bookmarks/$selected"
fi
