#!/bin/zsh
#
# This lists the existing bookmarks.
#
# Type:
#
#   bml
#
# ...to list the contents of $HOME/bookmarks.

ls -la "$HOME/.bookmarks" | grep "\->" | sed 's/ -> / /' | awk '{print $9, $10}'

