#!/bin/zsh
#
# This lets you quickly move up directories in your working tree.
#
# Type:
#
#   up <tab>
#
# ...to autocomplete on the directories in your working path.
#
# or:
#
#   up 2
#
# ...to move up that many directory levels.

re='^[1-9][0-9]*$'
if [[ $1 =~ $re ]]
then
    for _ in {1..$1}
    do
        cd ..
    done
elif [[ -z $1 ]]
then
    cd ..
else
    IFS='/' read -rA working_dir_path <<< "$(pwd)"
    working_dir_path=("${working_dir_path[@]:1:-1}")  # Strip leading blank (for root dir) and current directory.
    n_dirs=${#working_dir_path[@]}
    max_index=$((n_dirs - 1))
    for index in {$max_index..0}
    do
        dir="${working_dir_path[@]:$index:1}"
	if [[ "$dir" == "$1" ]]
        then
            target_dir_path=("${working_dir_path[@]:0:$((index + 1))}")
            target_dir=$(printf '/%s' "${target_dir_path[@]}")
	    cd "$target_dir" || exit 1
	    break
        fi
    done
    if [[ -z $target_dir ]]
    then
        echo "Location \"$1\" is not in the directory tree"
        return 1
    fi
fi
