#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..
echo
echo "Running all install scripts"

unameOut="$(uname -s)"
if [[ $unameOut == "Linux" ]]
then
    distroName="$(grep "^NAME=" /etc/os-release)"
    if [[ "$distroName" == *"Fedora"* ]]
    then
        echo "Adding rpm repositories"
	sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
	sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
	echo "Fedora install ready to go"
    elif [[ "$distroName" == *"Mint"* ]]
    then
        echo "Linux Mint install ready to go"
    else
        echo "Unknown Linux distribution: $distroName"
        exit 1
    fi
elif [[ $unameOut == "Darwin" ]]
then
    echo "Mac install ready to go"
else
    echo "Unknown kernel: $unameOut"
    exit 1
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
